version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - index_app
      - informativo_app
      - formulario_app
    restart: always

  index_app:
    build:
      context: .
      args:
        APP_DIR: "index"
    container_name: index_app
    volumes:
      - ./db:/app/db 
    environment:
      - FLASK_ENV=production
    depends_on:
      - sqlite_db
    restart: always

  informativo_app:
    build:
      context: .
      args:
        APP_DIR: "informativo"
    container_name: informativo_app
    volumes:
      - ./db:/app/db
    environment:
      - FLASK_ENV=production
    depends_on:
      - sqlite_db
    restart: always

  formulario_app:
    build:
      context: .
      args:
        APP_DIR: "formulario"
    container_name: formulario_app
    volumes:
      - ./db:/app/db
    environment:
      - FLASK_ENV=production
    depends_on:
      - sqlite_db
    restart: always

  sqlite_db:
    image: nouchka/sqlite3:latest
    container_name: sqlite_db
    volumes:
      - ./db:/root/db
    restart: always

volumes:
  db:
  monitoramento:
